name: MyRealHome
favicon: null
layout_spectrum: 0.8847871124744415
typography_spectrum: 0.6179636532906443
title: Real Estate. Real Different. MyRealHome.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3110b8'
    - '#ff9f00'
    - '#ffffff'
    - '#c37536'
    - '#905263'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
